### PR TITLE
HydroComponent new method ExecuteJs ordering client to execute JS scripts from server

### PR DESCRIPTION
**Pull request by taublast**
New HydroComponent method "ExecuteJs". Point is the data is tight to the component and not to the Client so I cannot use `Client.Invoke` here to achieve that.

Now I can order JS execution from inside the server component code.

Also solves the https://github.com/hydrostack/hydro/issues/49 "can't find a way to execute javascript from .net".

Explanation:

We have 2 main channels to render/deliver component data: static and online. 

A. Online is used when we update the component, here we can send component-related data (scripts in this case) with request headers. The `HydroComponentUpdate` native event is invoked here.

B. Static is used when the component is delivered along with the page content, would it be the initial page load or a partial page content load with `Location()`. The `HydroComponentInit` native event is invoked here.

Inside the hydro.js:
* Around the `HydroComponentUpdate` event we check if script data was sent with headers, and we execute them if any.
* Around the `HydroComponentInit` event we check if script data was embedded along with component HTML, and we execute them if any.

On server, inside the `HydroComponent` it's the same logic, for online rendering we send scripts with headers and for static rendering, we embed scripts inside component HTML to be executed later by hydro.js

What is also nice here, I think, is that we enhance the channel of communication server=>client to be used for more similar cases should they be needed.

And also this PR is adding some self-speaking native events, one could consume in their JS:

```js
 document.addEventListener('HydroLocation', function (event) {
     
     const { url, headers, selector, push, payload } = event.detail;
     
     console.log("HydroLocation:", event.detail);


 });

 document.addEventListener('HydroComponentUpdate', function (event) {

     const { componentId, name, url, type } = event.detail;
     
     console.log("HydroComponentUpdate: ", event.detail);

 });

 document.addEventListener('HydroRedirect', function (event) {

     const { url } = event.detail;
     
     console.log("HydroRedirect: ", event.detail);

 });

 document.addEventListener('HydroComponentInit', function (event) {

     const { component } = event.detail;
     
     console.log("HydroComponentInit: ", event.detail);

 });
```

### CODE REVIEW

**Comment by taublast** [comment]
Added a third commit with a quick fix that could be used along with with PR or apart: https://github.com/hydrostack/hydro/pull/57

**Comment by taublast** [comment]
Would re-create the PR i guess to avoid conflicts with recent pushes, but would need to hear your thoughts on the implementation if it globally suits Hydro philosophy. :) 
Actually using this a lot, for example, one component is calling an API endpoint and then:

```csharp
if (response.IsSuccessStatusCode)
{
		ExecuteJs("$(#callSuccessPopup).addClass('active')");
		return;
}
```

**Comment by kjeske** [comment]
The idea of executing JS from Hydro action is very good, thanks for that! There are 2 things I would suggest:
- I would switch from eval to dynamic script invocation in a script tag. The reason for that is the CSP policies that forbid using `eval` or `new Function()`. In hydro JS we would need to identify custom scripts and run them something like:

    ```js
    function injectScript(componentElement, scriptContent) {
        const script = element.createElement('script');
        script.innerHTML = scriptContent;
        componentElement.appendChild(script);
    }
    ```

    In the next step we need to support `nonce` attribute on the `script` tag, but it can be done later.

- I would also offer a `$component` parameter which is the component element. To do that the scriptContent would have to be wrapped with an additional function, like:

    ```js
    function injectScript(componentElement, scriptContent) {
        const script = element.createElement('script');
        script.innerHTML = `function($component) { ${scriptContent} }(document.getElementById(${componentElement.id}))`;
        componentElement.appendChild(script);
    }
    ```

**Comment by taublast** [comment]
Replaced eval with script injection for both "ExecuteJs" and "ajax-loaded scripts" cases, works nicely. 
Please take a look at https://github.com/hydrostack/hydro/pull/54/commits/6a5f871365029cb2c53e98b3779d98ebdebcb8a0?
Would need to re-create the pr then, as this one is coming from a branch i'm progressing with more changes out the scope, didn't expect this would ever happen.. :)

**Comment by kjeske** [comment]
Great! Awesome work.

Btw could we separate this PR a bit? I see here 3 features:
- Execute JS
- Adding target to Hydro Location (issue can be created)
- Cookie manager (can be removed from here since it's already in another PR)

Each one of them I will extensively test, so it will be easier if it's scoped down.

**Comment by taublast** [comment]
So the solved problem was for children components, when component B is inside component A, both are updated, and needed to exec script of appropriate components only. Problem gone.

passing parameter to scripts that come from ExecuteJs:

```js
function injectScript(componentElement, scriptContent) {
  const script = document.createElement('script');
  script.type = 'text/javascript';
  script.innerHTML = `
    (function($component) {
      ${scriptContent}
    })(document.getElementById("${componentElement.id}"));
  `;
  script.setAttribute('data-injected', 'true');
  componentElement.appendChild(script);
}
```

While fighting this needed to solve another problem, I saw that hydro-links and Location use fully-rendered (with layout) page to replace the `body`. We can now render only the content without Layout on server and insert it where the RenderBody() was expected. 
* App works faster when rendering just a page without layout 
* We have a freedom to choose where to insert ajax-loaded content instead of replacing the whole body: auto-inserted where `@Html.HydroBody(RenderBody())` or can pass `target` parameter to `Location`. Could also add one for hydro links HTML tag, didn't do it yet.

in _ViewStart:

```
@using Hydro

@{
    Layout = Context.IsHydroBoosted() ? null : "_Layout";
}
```
and in _Layout:

```
@Html.HydroBody(RenderBody())
```
instead of the usual
```
@RenderBody()
```

Why? To use auto-placement for links and location loads that would use _Layout=null.

At the same time added feats so along with normal `Location` signature we have also one with `target` element parameter.

Should split all this into different discussions now I guess as too many feats are now inside same branch. Looking forward to more discussions :)

**Pull request closed without merging**
